name: Deploy Angular to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Build Angular (prod)
        run: |
          npm ci
          npm run build -- --configuration production
          test -d dist/jwt-ng || (echo "::error::dist/jwt-ng not found" && exit 1)
          test -f dist/jwt-ng/index.html || (echo "::error::dist/jwt-ng/index.html missing; build didn’t produce an index.html" && exit 1)

      - name: Debug repo context
        run: |
          echo "Repo:    $GITHUB_REPOSITORY"
          echo "Branch:  $GITHUB_REF_NAME"
          echo "Event:   $GITHUB_EVENT_NAME"

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          # Using Deployment Token mode — ensure SWA policy is set to "Deployment token"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          production_branch: main

          # IMPORTANT: upload the built artifacts; do not trigger an Oryx rebuild
          skip_app_build: true
          app_artifact_location: "dist/jwt-ng"

          # No Functions API in this repo
          api_location: ""
