name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Build Angular (production)
        run: |
          npm ci
          npm run build -- --configuration production
          test -d dist/jwt-ng || (echo "::error::dist/jwt-ng not found" && exit 1)

      - name: Get Id Token
        id: idtoken
        uses: actions/github-script@v7
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          github_id_token: ${{ steps.idtoken.outputs.result }}
          production_branch: main
          app_location: "/"                # or "jwt-ng" if app in subfolder
          output_location: "dist/jwt-ng"   # or "jwt-ng/dist/jwt-ng"
          api_location: ""                 # none; separate App Service API
          skip_api_build: true
